credentials:
  username: Domain\username
  password: Su#per@S3cr3t!&

http_proxy_url: "proxy.url:8080"
https_proxy_url: "https://proxy.url:8080"

files:
  - path: /etc/environment
    variables:
      - http_proxy
      - https_proxy
      - proxy
      - qualys_http_proxy
  - path: /etc/wgetrc
    variables:
      - http_proxy
      - https_proxy
  - path: /home/username/.bashrc
    variables:
      - http_proxy
      - https_proxy
      - proxy
      - qualys_http_proxy
      - all_proxy
  - path: /home/username/.zshrc
    variables:
      - http_proxy
      - https_proxy
      - proxy
      - qualys_http_proxy
      - all_proxy
