name: Build & Publish Binaries

on:
  push:
    branches:
      - "master"

jobs:
  build-release-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./golang/src/go.mod"
          check-latest: true

      - name: Build Binary name
        run: BINARY_NAME=feynman-${{ matrix.GOOS }}-${{ matrix.GOARCH }}

      - name: Build Feynman
        run: |
          go version
          echo $BINARY_NAME
