name: Build & Publish Binaries

on:
  push:
    branches:
      - "master"

jobs:
  build-release-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./golang/src/go.mod"
          check-latest: true

      - name: Test version
        run: go version
