name: Build & Publish Binaries

on:
  push:
    branches:
      - "master"

jobs:
  build-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./golang/src/go.mod"
          check-latest: true

      - name: Build Binary name
        run: |
          BINARY_NAME=feynman-go-v0.1.0-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

      - name: Build Feynman
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: |
          cd ./golang/src
          go build -o $BINARY_NAME
          ls -larth

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: feynman-go-v0.1.0-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: ${{ github.workspace }}/golang/src/feynman-go-v0.1.0-${{ matrix.GOOS }}-${{ matrix.GOARCH }}

  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
